#include "macros.h"

const char *macros[5] = {"<LShift><Home></LShift><LCtrl>C</LCtrl><LCtrl>v</LCtrl><LCtrl>v</LCtrl>", "aAa<LShift>bBb</LShift>cCc", "ert!", "abc<Home>123", "aA<LShift><LShift>bB<Home>X</LShift>cC<junk></junk>"};

// Generated by software.