#include "mapping.h"
#include "keycode.h"

const uint16_t mapping[LAYER_COUNT][2*NUM_IN_PIN][NUM_OUT_PIN] = {
		{ // Layer: 1
		 {KC_MINUS, KC_0, KC_9, KC_8, KC_7, KC_6},
     {KC_LEFT_SQ_BRACKET, KC_P, KC_O, KC_I, KC_U, KC_Y},
     {KC_RIGHT_SQ_BRACKET, KC_SEMICOLON, KC_L, KC_K, KC_J, KC_H},
     {KC_APOSTROPHE, KC_SLASH, KC_PERIOD, KC_COMMA, KC_M, KC_N},
     {KC_EQUAL, KC_ENTER, KC_BACKSPACE, KC_SPACE, KC_RIGHT_CTRL, KC_RIGHT_SHIFT},

     {KC_ESCAPE, KC_1, KC_2, KC_3, KC_4, KC_5},
     {KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T},
     {KC_NEXT_LAYER, KC_A, KC_S, KC_D, KC_F, KC_G},
     {KC_PREV_LAYER, KC_Z, KC_X, KC_C, KC_V, KC_B},
     {KC_HOME, KC_END, KC_LEFT_SUPER, KC_SPACE, KC_LEFT_ALT, KC_LEFT_CTRL}
		},

		{ // Layer: 2
		 {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},

     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_NEXT_LAYER, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_PREV_LAYER, KC_L, KC_L, KC_L, KC_L, KC_L},
     {KC_L, KC_L, KC_L, KC_L, KC_L, KC_L}
		},

		{ // Layer: 3
		 {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},

     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_NEXT_LAYER, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_PREV_LAYER, KC_H, KC_H, KC_H, KC_H, KC_H},
     {KC_H, KC_H, KC_H, KC_H, KC_H, KC_H}
		},
};

// Generated by software. First row is slave mappings, second is master's.
